"""empty message

Revision ID: 66cbe05ff02b
Revises: 54d89f5f0d3e
Create Date: 2019-03-02 15:38:57.276547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66cbe05ff02b'
down_revision = '54d89f5f0d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta')
    # ### end Alembic commands ###
